version: '3'

services:

  adminer:
    image: adminer
    ports:
      - 8080:8080

  elections:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbdataapplication:/var/lib/mysql
    networks:
      - mynetapplication

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis

  admin:
    image: admin
    environment:
      - DATABASE_URL=elections
    depends_on:
      - applicationMigration
    ports:
      - 5001:5001
    networks:
      - mynetapplication

  user:
    image: user
    environment:
      - DATABASE_URL=elections
      - REDIS_URL=redis
    depends_on:
      - applicationMigration
    ports:
      - 5002:5002
    networks:
      - mynetapplication
      - redis

  daemon:
    image: daemon
    environment:
      - DATABASE_URL=elections
      - REDIS_URL=redis
    depends_on:
      - applicationMigration
    networks:
      - mynetapplication
      - redis

  applicationMigration:
    image: applicationmigration
    environment:
      - DATABASE_URL=elections
    depends_on:
      elections:
        condition: service_healthy
    networks:
      - mynetapplication

volumes:
 dbdataapplication:

networks:
  mynetapplication:
  redis:



