version: '3'

services:

  adminer:
    image: adminer
    ports:
      - 8080:8080

  elections:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbdataapplication:/var/lib/mysql
    networks:
      - mynetapplication
      - mynetdaemon

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynetdaemonredis
      - mynetuserredis

  admin:
    image: admin
    environment:
      - DATABASE_URL=elections
    depends_on:
      - applicationMigration
    ports:
      - 5001:5001
    networks:
      - mynetapplication

  user:
    image: user
    environment:
      - DATABASE_URL=elections
      - REDIS_URL=redis
    ports:
      - 5002:5002
    networks:
      - mynetapplication
      - mynetuserredis
    deploy:
      replicas:
        3

  daemon:
    image: daemon
    environment:
      - DATABASE_URL=elections
      - REDIS_URL=redis
    networks:
      - mynetdaemon
      - mynetdaemonredis

  applicationMigration:
    image: applicationmigration
    environment:
      - DATABASE_URL=elections
    networks:
      - mynetapplication

volumes:
 dbdataapplication:

networks:
  mynetapplication:
    driver: overlay
  mynetdaemon:
    driver: overlay
  mynetuserredis:
    driver: overlay
  mynetdaemonredis:
    driver: overlay



